### ISSUE TITLE
Summer 2019 Roadmap

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#115]
## Gather and finalize processing of existing datasets
- [x] BioTime #116
- [ ] Popler #95
- [x] BBS data wrangling #59
- [ ] Yenni et al. 2017 #119
- [ ] Compile listing of datasets #123

## Infrastructure 
- [ ] Plan automation for MATSS workflows #118
- [x] Test and merge in summary stats function #117
- [x] Template functionality for deploying a MATSS project #73
- [ ] general data processing utilities #96, #97 

## Misc:
- [ ] cache management #66
- [ ] document adding new datasets #77
- [x] document Maizuru dataset #60 
- [x] check Portal rodent data #14 
- [ ] environmental variable handling #88, #106
- [x] retriever interface testing #93, #94, #108
