### ISSUE TITLE
Roadmap (infrastructure paper)

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#147]
## Goals
Write up the work that has been done on MATSS so far - broaden awareness and usage of the package.

## Outline of the paper
* introduction and objectives for MATSS
* description of the datasets and data format
* demonstrate usage of the package for analysis
* summarize use cases, note advanced topics and point towards docs
* appendices for fiddly bits re: synchronizing, cluster deployment, automation
(see the [Getting Started](https://weecology.github.io/MATSS/articles/MATSS.html) vignette for an initial writeup with similar purpose)

## TODO
- [ ] finalize and document datasets #95, #119, #123, #148
- [ ] decide and implement general data processing utils #96, #97 
- [ ] decide and implement technical features:
    * cache management #66, #149
    * automation of plans #118 
    * cluster deployment

## Optional extras
- [ ] document contribution of new datasets #77
- [ ] environmental variable handling #88, #106

(this supersedes #115, so closing that issue)
