### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ha0ye** [weecology/MATSS#34]
Short-term goals: 
- [ ] basic summary stats and report, ~~#18~~ #73 
- [x] enhance the LDA report, #38
- [ ] documentation of various bits of the project, e.g. #23 
- [x] integrate code for a few more datasets into the package, e.g. #32, #33, BBS?
- [ ] add functions to format and clean datasets, ~~#39~~ #59 
- [ ] verify correctness of portal rodent data, #14
- [x] use a standard data format, #30 
- [ ] write up vision in docs for this github
- [ ] add examples to README on contributing data or analyses, #40

Medium-term goals: 
- [ ] complete remaining functionality for [LDATS](https://github.com/weecology/LDATS)
- [ ] figure out storage of results, github maybe not ideal but see https://github.com/ropensci/piggyback), #16 
- [ ] figure out automation to compute analyses, #15 
- [ ] add tests and documentation for the MATSS package component, #31 
- [ ] split analysis components over into https://github.com/weecology/MATSS-LDATS

Long-term goals (timeline TBD): 
- [ ] find funding opportunities, perhaps [NSF ABI](https://www.nsf.gov/pubs/2018/nsf18594/nsf18594.htm)
- [ ] discuss and draft up preprint(s)
- [ ] Build or adapt code for other analysis approaches and questions
- [ ] Build or adapt code to import other datasets
- [ ] Leverage modular structure to large-scale data analyses in other domains

(cc @gmyenni)

**Comment by ha0ye** [comment]
(This is now outdated, but I'm keeping this around until our next big planning meeting.)
